version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: file
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pashka93
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/file
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pashka93
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
